# Generated by Django 5.2.1 on 2025-05-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201112_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fraud_detection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_flagged_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
